/**
 * Created by Duc on 5/30/16.
 */
var en = {
    
    m_home: "Home",
    m_about: "About",
    m_features:"Features",
    m_price:"Pricing",
    m_manual: "User Manual",
    m_support:"Support",

    btn_signin: "SIGN IN",

    title_statement: "A comprehensive solution to manage the distribution system online by VIETTEL.",

    getting_started: "Getting started",
    getting_started_intro: "DMS PLUS, supported by the latest technology from Viettel, provide you with outstanding features which include online sales, monitoring and positioning support, most advanced sales model through distributors and many more...",
    btn_signup: "SIGN UP",

    about_us: "About Us",
    about_us_intro: "VIT2 - Viettel Information Techology Center is a subsidiary of Viettel Group. Our mission is “never stop making effort to create high quality products and services not only easy to use but fulfill clients’ requirements with desire to bring IT to every corner of life",

    valued_customer: "Valued Customer",

    watch_video: "Watch our video",

    features: "Features",
    features_intro: "Is an overall solution in managing the sale system from the company’s headquarters to the salesman and sales supervisor. It provides online data on sales results, KPI, location and route of salesman, which helps the manager to handle and make decisions...",
    features1: "Improve working quality",
    features1_intro: "Closely supervise the distribution system, effectively manage, control sales activity and inventory at distributors. ",
    features2: "Reduce cost",
    features2_intro1: "Reduce report activities.",
    features2_intro2: "Replace all manual documents by software platform.",
    features3: "Increase business efficiency",
    features3_intro: "Continuously and instantaneously update market information. Provide effective assistance tools accessing sales routes, salesperson’s capacity. ",
    features4: "Securities",
    features4_intro: "System is designed at a level of security that is consistent with the potential harm that could result from the loss, inaccuracy, alteration, unavailability of the data, resources.",

    pricing: "Pricing",
    pricing_basic: "Basic",
    pricing_business: "Business",
    pricing_professional: "Professional",
    pricing_month: "month",
    pricing_unit:"$",
    btn_select: "SELECT",
    pricing_module0: "Module Order",
    pricing_module1: "Module Routing",
    pricing_module2: "Module Visit",
    pricing_module3: "Module Supervise",
    pricing_module4: "Module Report",
    pricing_module5: "Module Promotion",
    pricing_module6: "Module Survey",
    pricing_module7: "Module Inventory",
    pricing_module8: "Module Exchange & Return",
    pricing_module9: "Module Check In",

    screenshot: "Screenshot",
    image1_title: "Login",
    image2_title: "Dashboard",
    image3_title: "Customer's general information",
    image4_title: "Customer's statistic information",
    image5_title: "Choose products",
    image6_title: "Visit customer",
    image7_title: "Visiting customer",
    image8_title: "Visit schedule map",
    image9_title: "Sales detail",
    image10_title: "Sales order detail",
    image11_title: "Register new customer",

    manual: "User Manual",
    manual_website: "Website",
    manual_website_admin: "Admin User Manual",
    manual_website_supervisor: "Supervisor User Manual",
    manual_website_distributor: "Distributor User Manual",
    manual_faq: 'FAQ',
    manual_mobile: "Mobile",
    manual_mobile_supervisor: "Supervisor User Manual",
    manual_mobile_salesman: "Salesman User Manual",

    support: "Support",
    support_intro: "Software Support protects your software investment and empowers your business with world class technical support expertise and comprehensive proactive support.",
    support_phone: "Telephone Support",
    support_phone_intro: "Instruct clients how to process simple incidents and how to use the software.",
    support_tech: "Technical Support",
    support_tech_intro: "Instruct clients to process software incidents remotely via teamviewer and phone with technical team.",
    support_onsite: "On-site Support",
    support_onsite_intro: "Providing directly assist at the place of incidents.",

    contact_us: "Contact us",
    contact_us_intro: "Need help with our solution or looking for more information? We're ready and waiting for your questions.",
    contact_phone: "Phone",
    contact_phone_content: "(+84) 462 881 188",
    contact_address: "Address",
    contact_address_content: "Floor 44, Keangnam Building, Pham Hung Street, Nam Tu Liem District, Hanoi, Vietnam.",
    contact_email: "Email",
    contact_email_content: "vit2_support@viettel.com.vn",

    copyright: "Copyright © 2016 VIETTEL GROUP. All rights reserved.",

    terms_of_use: "Terms of use",

    tou_h1: "1. Nguyên tắc chung",
    tou_h2: "2. Quy trình cấp tài khoản",
    tou_h3: "3. Quyền và nghĩa vụ của bên A",
    tou_h3_1: "Quyền của bên A:",
    tou_h3_2: "Nghĩa vụ của bên A:",
    tou_h4: "4. Quyền và nghĩa vụ của bên B",
    tou_h4_1: "Quyền của bên B:",
    tou_h4_2: "Nghĩa vụ của Bên B:",
    tou_h5: "5. Về phần mềm được cung cấp trong dịch vụ",
    tou_h6: "6. Tạm ngừng cung cấp dịch vụ",
    tou_h7: "7. Chấm dứt sử dụng dịch vụ",
    tou_h8: "8. Điều khoản áp dụng",

    tou_h1_p1: "Bằng việc truy cập và sử dụng các dịch vụ trên website: dmsplus.net bạn đã xác nhận rằng bạn đã đọc, hiểu, và đồng ý với mọi điều khoản trong Quy chế này.",
    tou_h1_p2: "Dịch vụ DMS.PLUS, các hình ảnh và trang web: dmsplus.net là sản phẩm thuộc Sở hữu trí tuệ của Tập đoàn Viễn thông Quân đội. Tất cả nhãn hiệu, logo, tên sản phẩm trong website này đều được đăng ký và được cấp bản quyền.",
    tou_h1_p3: "Quy chế hoạt động này được áp dụng cho Ban Quản lý dịch vụ DMS.PLUS (gọi tắt là Dịch vụ) và tất cả các thành viên đăng ký tham gia sử dụng các dịch vụ (bao gồm nhưng không giới hạn phần mềm, mã sử dụng…được nêu trên website: dmsplus.net).",
    tou_h1_p4: "Trong quy chế hoạt động này, Bên sử dụng dịch vụ DMS.PLUS được gọi là Bên A; Bên cung cấp dịch vụ DMS.PLUS được gọi là Bên B.",

    tou_h2_p1: "Khi Bên A có nhu cầu sử dụng Dịch vụ của Bên B, Bên A tiến hành đăng ký và điền đầy đủ, chính xác thông tin theo yêu cầu tạo tài khoản tại địa chỉ website: dmsplus.net",
    tou_h2_p2: "- Hệ thống sẽ gửi mã đăng nhập và mật khẩu của tài khoản admin đến cho khách hàng.",
    tou_h2_p3: "- Khách hàng vào hệ thống, tạo các tài khoản cần thiết của doanh nghiệp (kế toán bán hàng, giám sát, nhân viên bán hàng, ...) chọn gói cước sử dụng và kích hoạt các tài khoản.",

    tou_h3_p1: "Được sử dụng Dịch vụ.",
    tou_h3_p2: "Khiếu nại về những sai sót trong việc cung cấp Dịch vụ của Bên B theo quy định của pháp luật.",
    tou_h3_p3: "Yêu cầu Bên B bảo mật các thông tin sử dụng Dịch vụ của Bên A.",
    tou_h3_p4: "Quản lý, sử dụng tài khoản Dịch vụ theo đúng hướng dẫn của Bên B và quy định của pháp luật. Tôn trọng quyền Sở hữu trí tuệ khi sử dụng phần mềm và các tiện ích Dịch vụ được Bên B cung cấp.",
    tou_h3_p5: "Có trách nhiệm xử lý bất cứ tranh chấp nào liên quan đến việc sử dụng thương hiệu, tên và nội dung thông tin đã đăng ký, sử dụng qua hệ thống của Bên B. Không sử dụng Dịch vụ để kinh doanh trái phép dưới bất kỳ hình thức nào theo pháp luật quy định.",
    tou_h3_p6: "Thực hiện tất cả các biện pháp cần thiết để bảo mật Dịch vụ, không được phép truy cập trái phép vào mạng lưới của Bên B.",
    tou_h3_p7: "Hoàn toàn chịu trách nhiệm cho bất kỳ và tất cả các hoạt động diễn ra trong tài khoản của Bên A thực hiện khi sử dụng Dịch vụ và các rủi ro có thể có khi mất quyền truy cập.",
    tou_h3_p8: "Phối hợp với Bên B giải quyết các lỗi phát sinh (nếu có) trong quá trình sử dụng Dịch vụ.",

    tou_h4_p1: "Kiểm tra, kiểm soát việc sử dụng Dịch vụ và tài khoản DMS.ONE của Bên A theo quy định của pháp luật.",
    tou_h4_p2: "Tạm ngừng hoặc chấm dứt Dịch vụ theo quy định trong Quy chế sử dụng này.",
    tou_h4_p3: "Sở hữu trí tuệ đối với tất cả hình ảnh, tài liệu, phần mềm và tính năng Dịch vụ. Mọi quyền sử dụng dịch vụ Bên B cấp cho Bên A không đồng nghĩa với quyền sở hữu trí tuệ về dịch vụ.",
    tou_h4_p4: "Nâng cấp các phiên bản, tính năng cho phần mềm/Dịch vụ: Bên B có thể thêm, xóa, sửa hoặc tạm ngừng sử dụng Dịch vụ để cải tiến và hoàn thiện phần mềm.",
    tou_h4_p5: "Gửi các thông báo Dịch vụ, quản trị và các thông tin khác cho Bên A phục vụ việc sử dụng Dịch vụ.",
    tou_h4_p6: "Cung cấp Dịch vụ và đảm bảo chất lượng, duy trì hoạt động ổn định của mạng lưới, hệ thống kết nối với Dịch vụ để đáp ứng các yêu cầu sử dụng Dịch vụ của khách hàng.",
    tou_h4_p7: "Giữ bí mật thông tin Dịch vụ và khách hàng của Bên A, trừ trường hợp đặc biệt theo quy định của pháp luật.",
    tou_h4_p8: "Lưu trữ dữ liệu đã được đồng bộ lên website: dmsone.vn của Bên A.",
    tou_h4_p9: "Hỗ trợ hướng dẫn sử dụng và nghiệp vụ trong suốt quá trình sử dụng Dịch vụ của Bên A (không áp dụng khi Bên A sử dụng các gói dùng thử miễn phí).",
    tou_h4_p10: "Giải quyết khiếu nại của Bên A theo đúng quy định của pháp luật.",

    tou_h5_p1: "Dịch vụ bao gồm phần mềm có thể tải xuống, phần mềm này có thể được cập nhật trên thiết bị của Bên A ngay khi có sẵn một phiên bản hoặc tính năng mới.",
    tou_h5_p2: "Bằng việc Bên A thanh toán theo gói cước đăng ký, Bên B kích hoạt các tài khoản Bên A đã đăng ký tương ứng với thời gian đăng ký, sử dụng trong phạm vi lãnh thổ Việt Nam.",
    tou_h5_p3: "Bên A không được phép sao chép, sửa đổi, phân phối, bán hoặc cho thuê bất kỳ phần nào trong Dịch vụ của Bên B hoặc các phần mềm có trong Dịch vụ đó.",
    tou_h5_p4: "Bên A hoàn toàn chịu trách nhiệm đối với việc mất mát thông tin/ dữ liệu khi sử dụng phần mềm do lỗi của Bên A thao tác tại máy tính của mình.",
    tou_h5_p5: "Bên B không chịu trách nhiệm về khoản lợi nhuận, doanh thu hoặc dữ liệu bị mất mát, thiệt hại tài chính hoặc các thiệt hại gián tiếp do việc sử dụng Dịch vụ tại máy tính của Bên A. Trong phạm vi được pháp luật cho phép, toàn bộ trách nhiệm pháp lý của Bên B được giới hạn ở số tiền mà Bên A đã thanh toán cho Bên B để sử dụng Dịch vụ hoặc cung cấp lại Dịch vụ cho Bên A.",

    tou_h6_p1:"Bên B có quyền đơn phương tạm ngừng một phần hoặc toàn bộ Dịch vụ nếu Bên A vi phạm một trong các điều được quy định tại phần Nghĩa vụ của Bên A theo Quy chế này hoặc Bên B phát hiện thấy có dấu hiệu bất thường trong quá trình hợp tác với Bên A mà kết quả có thể dẫn đến thiệt hại cho Bên B hoặc gây ảnh hưởng bất lợi đến khách hàng (Bên B không có nghĩa vụ phải đưa ra bằng chứng để chứng minh). Trong trường hợp này, Bên B có thể tiến hành tạm ngừng việc cung cấp Dịch vụ cho Bên A hoặc các nghĩa vụ khác có liên quan của Bên B theo Quy chế này.",

    tou_h7_p1:"Bên A có quyền chấm dứt sử dụng Dịch vụ bằng việc ngừng đăng nhập và nạp tiền vào hệ thống Dịch vụ của Bên B.",
    tou_h7_p2:"Bên B có quyền đơn phương chấm dứt việc sử dụng Dịch vụ của Bên A trong trường hợp theo yêu cầu của cơ quan Nhà nước có thẩm quyền hoặc quy định khác của pháp luật.",
    tou_h7_p3:"Bên B không có trách nhiệm hoàn trả bất kỳ khoản tiền nào mà bên A đã nạp vào hệ thống Dịch vụ của Bên B.",

    tou_h8_p1:"Mọi tranh chấp phát sinh giữa hai Bên sẽ được giải quyết trên cơ sở thương lượng. Trường hợp không đạt được thỏa thuận như mong muốn, một trong hai Bên có quyền đưa vụ việc ra Tòa án có thẩm quyền tại Việt Nam để giải quyết.",
    tou_h8_p2:"Các điều khoản này được thực hiện trên tinh thần tự nguyện. Bên B có quyền sửa đổi và thay thế.",
    tou_h8_p3:"Quy chế này bằng cách thông báo lên website: dmsone.vn cho các thành viên được biết. Quy chế sửa đổi có hiệu lực kể từ ngày Quyết định về việc sửa đổi Quy chế có hiệu lực. Nếu Bên A không đồng ý với một trong các điều khoản sửa đổi thì có thể ngừng việc sử dụng Dịch vụ. Việc Bên A tiếp tục sử dụng Dịch vụ sau khi Quy chế sửa đổi được công bố và thực thi đồng nghĩa với việc họ đã chấp nhận Quy chế sửa đổi này.",

}
