/**
 * Created by Duc on 5/30/16.
 */

 var po = {


m_home: "INÍCIO ", 
m_about: "SOBRE ", 
m_features: "CARACTERÍSTICAS ", 
m_price: "PREÇOS ", 
m_manual: "MANUAL DO USUÁRIO ", 
m_support: "APOIO ", 
btn_signin: "INICIAR A SESSÃO", 
title_statement: "Uma solução abrangente para gerenciar o sistema de distribuição on-line por VIETTEL.", 
getting_started: "Para começar", 
getting_started_intro: "DMS PLUS, apoiado pela tecnologia mais recente da Viettel, lhe fornecer recursos pendentes que incluem as vendas online, monitoramento e suporte de posicionamento, modelo de vendas mais avançados através de distribuidores e muitos mais ...", 
btn_signup: "INSCREVER-SE", 
about_us: "Sobre nós", 
about_us_intro: "Viettel Information Techology Center é uma subsidiária do Grupo Viettel. Nossa missão é nunca parar de fazer esforço para criar produtos de alta qualidade e serviços não só fácies de usar, mas cumprir os requisitos dos clientes com o desejo de trazê-lo para todos os cantos da vida", 
valued_customer: "Cliente valorizado", 
watch_video: "Assista nosso video", 
features: "Características", 
features_intro: "É uma solução global na gestão do sistema de venda a partir da sede da empresa para o vendedor e vendas supervisor. Ele fornece dados on-line sobre as resultados de vendas, KPI, localização e rota de vendedor, o que ajuda o gerente de manusear e tomar decisões ...", 
features1: "Melhorar a qualidade do trabalho", 
features1_intro: "Intimamente supervisionar o sistema de distribuição, gerir eficazmente, a atividade de vendas de controle e estoques em distribuidores.", 
features2: "Reduzir o custo", 
features2_intro1: "Reduzir as atividades de relatório. ", 
features2_intro2: "Substituir todos os documentos manuais por plataforma de software", 
features3: "Aumentar a eficiência dos negócios", 
features3_intro: "Continuamente e instantaneamente atualizar informações de mercado. Fornecer ferramentas eficazes de assistência acessando rotas de vendas, a capacidade do vendedor", 
features4: "Valores mobiliários", 
features4_intro: "O sistema é projetado em um nível de segurança que é consistente com o dano potencial que pode resultar da perda, imprecisão, alteração, a indisponibilidade dos dados, recursos.", 
pricing: "PREÇOS", 
pricing_basic: "BÁSICO", 
pricing_business: "NEGÓCIO", 
pricing_professional: "PROFiSSIONAL", 
pricing_month: "mês", 
pricing_unit: "$", 
btn_select: "Selecionar", 
pricing_module0: "Módulo de Ordem", 
pricing_module1: "Módulo de Rota", 
pricing_module2: "Módulo de visita", 
pricing_module3: "Módulo de Supervisionar", 
pricing_module4: "Módule do Relatório", 
pricing_module5: "Módulo de Promoção", 
pricing_module6: "Módulo  de Pesquisa", 
pricing_module7: "Módulo de Inventário", 
pricing_module8: "Módulo de Troca e Devolução", 
pricing_module9: "Módulo de Check In", 
screenshot: "Screenshot", 
image1_title: "Login", 
image2_title: "Dashboard", 
image3_title: "Customer's general information", 
image4_title: "Customer's statistic information", 
image5_title: "Choose products", 
image6_title: "Visit customer", 
image7_title: "Visiting customer", 
image8_title: "Visit schedule map", 
image9_title: "Sales detail", 
image10_title: "Sales order detail", 
image11_title: "Register new customer", 
manual: "Manual do usuário", 
manual_website: "Website", 
manual_website_admin: "Manual do Utilizador de Administração", 
manual_website_supervisor: "Manual do supervisor", 
manual_website_distributor: "Manual do distribuidor", 
manual_faq: "FAQ", 
manual_mobile: "MÓVEL", 
manual_mobile_supervisor: "Manual do supervisor", 
manual_mobile_salesman: "Manual do distribuidor", 
support: "Apoio ", 
support_intro: "Suporte de Software protege o seu investimento em software e capacita sua empresa com experiência de classe mundial apoio técnico e suporte proativo abrangente.", 
support_phone: "Suporte por telefone", 
support_phone_intro: "Instruir os clientes como processar incidentes simples e como usar o software.", 
support_tech: "Suporte técnico", 
support_tech_intro: "Instruir os clientes a processar incidentes de software remotamente via TeamViewer e telefone com a equipe técnica.", 
support_onsite: "Suporte no local", 
support_onsite_intro: "Fornecer directamente assistência no local de incidentes", 
contact_us: "CONTACTE-NOS", 
contact_us_intro: "Precisa de ajuda com a nossa solução ou à procura de mais informações? Estamos prontos e esperando por suas perguntas.", 
contact_phone: "Telefone", 
contact_phone_content: "", 
contact_address: "Endereço", 
contact_address_content: "", 
contact_email: "Email", 
contact_email_content: "", 
copyright: "Copyright © 2016 VIETTEL GROUP. All rights reserved.", 
terms_of_use: "Termos de uso", 
su_title: "INSCREVER-SE", 
su_company_info: "Informações da empresa", 
su_company_code: "Código da Empresa", 
su_company_name: "Nome da Empresa", 
su_representative: "Representante", 
su_phone_number: "Número de Telefone", 
su_email_address: "Email", 
su_company_address: "Endereço da Empresa", 
su_register_services: "Registar serviços", 
su_number_receive: "Receber senha no número de telefone", 
su_reference_id: "Referência ID", 
su_captcha: "Captcha", 
btn_sign_up: "Inscrever-se", 
btn_cancel: "Cancelar", 
tou_h1: "1. Os Princíspios gerais", 
tou_h2: "2. Processo de provedor Conta", 
tou_h3: "3. Os direitos e obrigações de Parte A", 
tou_h3_1: "Os direitos de Parte A", 
tou_h3_2: "As obrigações de Parte  A", 
tou_h4: "4. Os direitos e obrigações de Parte B", 
tou_h4_1: "Os direitos de Parte B", 
tou_h4_2: "As obrigações de Parte  B", 
tou_h5: "5. O software é fornecido no serviço", 
tou_h6: "6. Suspender a prestação de serviços", 
tou_h7: "7. Rescisão dos usuários do serviço", 
tou_h8: "8. Termos se aplicam", 
tou_h1_p1: "Ao acessar e usar os serviços no site: dmsplus.net você reconhece que leu, entendeu e concorda com todas as disposições do presente Regulamento.",  
tou_h1_p2: "Serviço DMS.PLUS, imagens e páginas da web: dmsplus.net é o produto da Propriedade Intelectual da Viettel Mobile. Todas as marcas, logotipos, nomes de produtos deste site são registrados e licenciados.", 
tou_h1_p3: "Regulamento operação é aplicável aos serviços de Conselho de Administração DMS.PLUS (referidas como Serviço) e todos os participantes inscritos para usar o serviço (incluindo mas não limitado a software, código usar ... ainda disponíveis: dmsplus.net). ", 
tou_h1_p4: "Neste regulamentos de funcionamento, os partidos usar o DMS.PLUS serviços de chamada do Parte A; Parte prestadores de serviços DMS.PLUS chamado Parte B", 
tou_h2_p1: "Quando o parte A quer utilizar os serviços do partido B,o partido A regista e completa as informações exatamente, conforme solicitado a criar uma conta no site endereço: dmsplus.net", 
tou_h2_p2: "O sistema irá enviar o código de login e senha para a conta de administrador para os clientes.", 
tou_h2_p3: "Os clientes acessar o sistema e fazer a conta necessária do (contabilidade de vendas, monitoramento, vendedores, ...) de negócios, selecione o pacote de usar e ativar a conta", 
tou_h3_p1: "Usar serviço .", 
tou_h3_p2: "As queixas sobre erros na prestação de serviços de parte B, conforme estipulado por lei.", 
tou_h3_p3: "Solicitado o Parte B a segura  informação dos utilizados de serviço  pelo Parte A.", 
tou_h3_p4: "Conta de gestão, usuário do serviço de acordo com as instruções do Parte B e as disposições de direito. Respeitando pelos direitos de propriedade intelectual para usar serviços de software e utilitários fornecidos pelo Parte B.", 
tou_h3_p5: "São responsáveis pela manipulação de qualquer controvérsia relativa à utilização de marcas comerciais, nomes e conteúdo da informação registrada, use o sistema de Parte B. Não use o serviço para o negócio ilegal de qualquer forma da lei.", 
tou_h3_p6: "Executar todas as medidas necessárias para os serviços de segurança, não é permitido o acesso não autorizado à rede do Parte B.", 
tou_h3_p7: "Inteiramente responsável por todas e quaisquer atividades que ocorram na sua conta quando o Partido A para usar o Serviço e o possível risco de perder o acesso. ", 
tou_h3_p8: "Coordenação com os de liquidação decorrentes erros do Parte B (se houver) no decurso da utilização do Serviço.", 
tou_h4_p1: "Verificar, controlar serviços de uso e conta DMS.Plus do Parte A, conforme estipulado por lei.", 
tou_h4_p2: " Pausar ou encerrar o serviço, tal como estipulado no regulamento de utilização.", 
tou_h4_p3: "Propriedade intelectual para todos os recursos de imagens, documentos, software e serviços. Todos os direitos de usar o serviço para Parte A Parte B não é sinônimo com os direitos de propriedade intelectual de serviço.", 
tou_h4_p4: "Atualizar versões, recursos de software / serviços: Parte B pode adicionar, excluir, modificar ou suspender o uso do Serviço para melhorar e aperfeiçoar o software.", 
tou_h4_p5: "Enviar o serviço de notificação, administração e outras informações para um parte de serviço da utilização do Serviço.", 
tou_h4_p6: "Fornecimento de serviço e garantia de qualidade, para manter a operação estável da rede, o sistema conectado ao serviço para atender a exigência de utilização de serviço ao cliente.", 
tou_h4_p7: "Manter as informações confidenciais e atendimento ao cliente do Parte A, exceto em casos especiais previstos na lei.", 
tou_h4_p8: "Arquivar dados que tenha sido sincronizado com o site dmsone.vn do Parte A", 
tou_h4_p9: "Suportar manual e profissional durante a utilização dos Serviços por parte do Parte A (não se aplica com Parte A pacote de teste gratuito).", 
tou_h4_p10: "Resolução de queixas por Parte A, de acordo com a lei.", 
tou_h5_p1: "O serviço inclui software para baixar, este software pode ser atualizado no dispositivo quando o Parte A está disponível uma nova versão ou recurso.", 
tou_h5_p2: "Pagamento por o Parte A no âmbito do pacote registada, contas de ativação do Parte B  registrado parte A correspondente ao período de subscrição, utilizados no território do Portugal", 
tou_h5_p3: "O Parte A não é permitido copiar, modificar, distribuir, vender ou alugar qualquer parte do software do serviço ou Parte B incluído nesse Serviço.", 
tou_h5_p4: "O Parte A é o único responsável pela perda de informações / dados durante a utilização culpa do software do Partido A manipulação em seu computador.", 
tou_h5_p5: "Parte B não é responsável por lucros, receitas ou perda de dados, perdas financeiras ou danos indirectos resultantes da utilização de serviços de informática do Parte A. Na medida do permitido por lei, toda a responsabilidade da Parte B é limitada ao valor que o Parte A para a Parte B pagou a usar o serviço ou o serviço fornecido para a Parte A.", 
tou_h6_p1: "Parte B tem o direito de suspender unilateralmente parte ou a totalidade do Serviço se o partido A viola uma das condições especificadas no Obrigações seção de um partido no presente regulamento ou do partido B é encontrado para ter anormalidades no processo colaborativo com um partido de que os resultados podem levar a danos ao partido B ou afetar negativamente os clientes (Parte B não tem nenhuma obrigação de apresentar provas para provar). Neste caso, o Partido B pode continuar a suspender a prestação de serviços para o partido A ou outras obrigações relacionadas do partido B abrigo do presente regulamento.", 
tou_h7_p1: "Uma das partes pode rescindir o uso dos Serviços por o sinal de parada e recarregar o sistema do Partido B. Serviço", 
tou_h7_p2: "Parte B tem o direito de rescindir unilateralmente o uso dos Serviços pelo Partido A, no caso, a pedido de organismos estatais disposições competentes ou outros de direito.", 
tou_h7_p3: "Parte B não é responsável pelo pagamento de qualquer montante que o partido A tenha sido carregado no sistema do Serviço do Partido B.", 
tou_h8_p1: "Qualquer litígio entre as partes será resolvido com base na negociação. Onde não houver acordo como esperado, qualquer uma das partes tem o direito de levar o caso a um tribunal competente no Vietnã para a liquidação.", 
tou_h8_p2: "Estas disposições são feitas no espírito de voluntariado. Parte B tem o direito de alterar e substituir este presente regulamento através de um aviso no site: dmsplus.net conhecido para os membros. ", 
tou_h8_p3: "Regulamento alterado com efeitos a partir da data da decisão sobre a alteração do regulamento entra em vigor. Se um parte não concordar com a modificação dos termos, eles podem deixar de usar os Serviços. O Parte A utilização dos Serviços continuou depois de um regulamento revisto publicado e implementado significava que eles tiveram que aceitar o presente regulamento alteração."
 }
 var es = {

    m_home: "CASA ", 
m_about: "SOBRE ", 
m_features: "CARACTERISTICAS ", 
m_price: "PRECIO ", 
m_manual: "MANUAL DEL USUARIO ", 
m_support: "SOPORTE ", 
btn_signin: "REGISTRARSE", 
title_statement: "Una solución compresiva para gestionar el sistema de distribución en línea por VIETTEL.", 
getting_started: "PARA COMENZAR", 
getting_started_intro: "DMS PLUS, con el apoyo de la última tecnología de Viettel, le proporcionan características de calidad, incluyendo las ventas en línea, monitoreo y soporte de posicionamiento, modelo de ventas más avanzada a través de distribuidores y muchos más ...", 
btn_signup: "Registrate", 
about_us: "sobre nosotros", 
about_us_intro: "Centro de techologia informatica de Viettel es una subsidiaria de Viettel Group. Nuestra misión es nunca dejar de hacer esfuerzos para crear los productos de alta calidad y servicios no sólo es fácil de usar, pero cumplir con los requisitos de los clientes con el deseo de llevarla a todos los rincones de la vida", 
valued_customer: "Estimado Cliente", 
watch_video: "Ver nuestro video", 
features: "CARACTERISTICA", 
features_intro: "Es una solución global en la gestión del sistema de venta desde la sede de la compañía para el vendedor y supervisor de venta. Proporciona datos en línea sobre los resultados de ventas, KPI, la ubicación y la ruta de vendedor, lo que ayuda al gerente de manejar y tomar decisiones …", 
features1: "Mejorar la calidad del trabajo", 
features1_intro: "Supervisar atentamente el sistema de distribución, gestionar efectivamente, controlar actividad de las ventas, y inventar a los distribuidores.", 
features2: "Reducir el costo", 
features2_intro1: "Reducir las actividades de reporte", 
features2_intro2: "Reemplazar todos los documentos manuales por la plataforma de software", 
features3: "Aumentar la eficiencia del negocio", 
features3_intro: "Continuamente y instantáneamente actualizar la información de mercado. Proporcionar herramientas efectivas de asistencia con el acceso de rutas de venta, la capacidad del vendedor", 
features4: "Seguridades", 
features4_intro: "El sistema está diseñado con un nivel de seguridad que es consistente con el daño potencial que podría resultar de la pérdida, la inexactitud, alteración, falta de disponibilidad de los datos, los recursos.", 
pricing: "Precio", 
pricing_basic: "Basico", 
pricing_business: "Negocio", 
pricing_professional: "PROFESIONAL", 
pricing_month: "mes", 
pricing_unit: "$", 
btn_select: "selecto", 
pricing_module0: "Modulo de orden", 
pricing_module1: "Modulo de ruta", 
pricing_module2: "Modulo de visita", 
pricing_module3: "Modulo de supervision", 
pricing_module4: "Modulo de reporte", 
pricing_module5: "Modulo de promocion", 
pricing_module6: "Modulo de encuesta", 
pricing_module7: "Modulo de inventario", 
pricing_module8: "Modulo de intercambio y devolucion", 
pricing_module9: "Modulo de entrada", 
screenshot: "CAPTURAS DE PANTALLA", 
image1_title: " Login", 
image2_title: " Dashboard", 
image3_title: " Customer's general information", 
image4_title: " Customer's statistic information", 
image5_title: " Choose products", 
image6_title: " Visit customer", 
image7_title: " Visiting customer", 
image8_title: " Visit schedule map", 
image9_title: " Sales detail", 
image10_title: " Sales order detail", 
image11_title: " Register new customer", 
manual: "Manual de usuario", 
manual_website: "Sitio de wed", 
manual_website_admin: "Administrador de manual del usuario", 
manual_website_supervisor: "Supervisor de manual del usuario", 
manual_website_distributor: "Distribuidor de manual del usuario", 
manual_faq: "FAQ", 
manual_mobile: "Movil", 
manual_mobile_supervisor: "Supervisor de manual del usuario", 
manual_mobile_salesman: "Distribuidor de manual del usuario", 
support: "SOPORTE", 
support_intro: "Prometemos el máximo apoyo para su empresa con la experiencia y las normas técnicas internacionales.", 
support_phone: "Soporte telefonico", 
support_phone_intro: "Instruir a los clientes cómo procesar incidentes simples y cómo utilizar el software.", 
support_tech: "Soporte tecnico", 
support_tech_intro: "Instruir a los clientes para procesar incidentes de software de forma remota a través de TeamViewer y teléfono con equipo técnico.", 
support_onsite: "Soporte en Sitio", 
support_onsite_intro: "Proporcionar directamente el asistente en el lugar de los incidentes", 
contact_us: "Contactenos", 
contact_us_intro: "¿Necesita ayuda con nuestra solución o en busca de más información? Estamos listos ya y esperando de sus preguntas.", 
contact_phone: "Telefono", 
contact_phone_content: "123", 
contact_address: "Direccion", 
contact_address_content: "878, Calle 21, San Isidrio, Lima, Peru", 
contact_email: "correo electronico", 
contact_email_content: "support@bitel.com.pe", 
copyright: "Derechos de autor @ 2016 Viettel GRUPO. TODOS LOS DERECHOS RESERVADOS", 
terms_of_use: "Terminos de uso", 
su_title: "Registrate", 
su_company_info: "Informacion de empresa", 
su_company_code: "Codigo de Empresa", 
su_company_name: "Nombre de Empresa", 
su_representative: "Represente", 
su_phone_number: "Numero de Telefono", 
su_email_address: "Correo Electronico", 
su_company_address: "Direccion de Empresa", 
su_register_services: "Registrar los Servicios", 
su_number_receive: "Numero Telefonico Recibe la Contraseña", 
su_reference_id: "Carnet de Identidad de Referencia", 
su_captcha: "Codigo de Imagen", 
btn_sign_up: "Registrate", 
btn_cancel: "Cancelar", 
tou_h1: "1. Términos Generales", 
tou_h2: "2. Proceso de crear cuenta", 
tou_h3: "3. Los derechos y obligaciones de la A ", 
tou_h3_1: "Derechos de la Parte A", 
tou_h3_2: "Obligaciones de la Parte A", 
tou_h4: "4. Los derechos y obligaciones de la Parte B", 
tou_h4_1: "Derechos de la Parte B", 
tou_h4_2: "Obligaciones de la Parte B", 
tou_h5: "5. Sobre el software que se proporciona en el servicio", 
tou_h6: "6. Suspender la prestación de los servicios", 
tou_h7: "7. La terminación del servicio", 
tou_h8: "8. Articulos aplicados", 
tou_h1_p1: "Al acceder y utilizar los servicios en el sitio de web: dmsplus.net usted reconoce que ha leído, entendido y estar de acuerdo con todas las disposiciones en este Reglamento.", 
tou_h1_p2: "Servicios DMS.PLUS, imágenes y páginas web: dmsplus.net es el producto de la Propiedad Intelectual de grupo Viettel. Todas las marcas, logotipos, nombres de productos mencionados en este sitio de web están registrados y autorizados.", 
tou_h1_p3: "Este reglamento de funcionamiento es aplicado a la junta de gestión de los servicios DMS.PLUS (conocidas como Servicio) y todos los participantes registrados para utilizar el servicio (incluyendo, pero no limitado a software, código utilizado ...  mencionado en wed: dmsplus.net).", 
tou_h1_p4: "En este reglamento de operación, las partes utilizan los servicios de DMS.PLUS llamada Parte A; Proveedores de servicios DMS.PLUS llamado la Parte B.", 
tou_h2_p1: "Cuando la Parte A tiene que utilizar los servicios de la Parte B, la Parte A realiza el registro e llena completamente y exactamente las informaciones segun la solicitud de crear una cuenta en la dirección en sitio de web: dmsplus.net", 
tou_h2_p2: "- El sistema enviará el código de usuario y la contraseña de la cuenta de administrador a los clientes.", 
tou_h2_p3: "- El cliente entra el sistema, crear las cuentas necesarias de la empresa (contabilidad de ventas, seguimiento, vendedores, ...), seleccione el paquete de usado y activar la cuenta.", 
tou_h3_p1: "Usar los servicios. ", 
tou_h3_p2: "Reclamar acerca de los errores en la prestación de servicios de la Parte B según lo estipulado por la ley.", 
tou_h3_p3: "Solicitar Parte B la seguridad de información utilizado por la Parte A.", 
tou_h3_p4: "Gestiónar, usar la cuenta de servicio de acuerdo a las instrucciones de la Parte B y las disposiciones de la ley. Respetar de los derechos de propiedad intelectual para utilizar los servicios de software y de servicios proporcionados por la Parte B.", 
tou_h3_p5: "Es responsable de solucionar cualquier controversia relativa a la utilización de marcas comerciales, nombres y contenido de la información registrada, utilizar el sistema de la Parte B. No utilizar el Servicio para cualquier negocio ilegal bajo cualquier forma prescrita por la ley. ", 
tou_h3_p6: "Realizar todas las medidas necesarias para la seguridad de los servicios, no se permite el acceso no autorizado a la red de la Parte B.", 
tou_h3_p7: "Totalmente es responsable de cualquier y todas las actividades que ocurran en su cuenta de la Parte A realizado cuando usa el Servicio y el posible riesgo de perder el acceso.", 
tou_h3_p8: "Coordinar con la Parte B para solucionar los errores surgidos (si hay) en el curso de la utilización del Servicio.", 
tou_h4_p1: "Comprobar, controlar el uso de los servicios y cuenta DMS.ONE de la Parte A según lo estipulado por la ley.", 
tou_h4_p2: "Suspensión o terminación del servicio segun el Reglamento establecido en regulacion de este uso.", 
tou_h4_p3: "La propiedad intelectual es para todas las características de imágenes, documentos, software y servicios. Todos los derechos para utilizar el servicio de la Parte B entrega a la parte A no es sinónimo de los derechos de propiedad intelectual de servicio.", 
tou_h4_p4: "Actualizar las versiones, las características de software / servicios: Parte B puede añadir, borrar, modificar o suspender el uso del Servicio para mejorar y perfeccionar el software.", 
tou_h4_p5: "Enviar la notificación del servicio, la administración, y otra información a la Parte A para servir el uso del Servicio.", 
tou_h4_p6: "Prestar el servicio y garantizar la calidad, mantener un funcionamiento estable de la red, el sistema conectado al servicio para satisfacer el requisito de utilizar el servicio del cliente.", 
tou_h4_p7: "Mantener la información confidencial del servicio y del cliente de la Parte A, excepto en casos especiales previstos en la ley.", 
tou_h4_p8: "Guardar los datos que se han sincronizado a la página web: dmsone.vn de la Parte A.", 
tou_h4_p9: "Soportar y guiar el uso y profesionalidad durante el uso de los servicios de la Parte A (excepto si se usa paquete de prueba gratis por la Parte A).", 
tou_h4_p10: "Solucionar las quejas de la Parte A según lo estipulado por la ley.", 
tou_h5_p1: "El servicio incluye software descargable, este software puede ser actualizado en el dispositivo de la parte A tan pronto como una versión o nuevas características estan disponible.", 
tou_h5_p2: "El pago realizdo por la Parte A segun el paquete registrado, la Parte B activa las cuentas registrado para Parte A, correspondiente al período de suscripción, que se utiliza en el territorio de España.", 
tou_h5_p3: "No está permitido la parte A realiza copiar, modificar, distribuir, vender o arrendar ninguna parte del Servicio de parte B o software en ese servicio", 
tou_h5_p4: "La parte A es el único responsable de la pérdida de información / datos durante el uso del software por la culpa de Parte A que manipula en su computadora.", 
tou_h5_p5: "Parte B no es responsable de las ganancias, ingresos o perdidas de datos, pérdidas financieras o daños indirectos resultantes de la utilización de los servicios informáticos de Parte A. En la medida permitida por la ley, la responsabilidad total de la Parte B se limita por la cantidad de dinero realizado por la Parte A a la Parte B para la utilización del Servicio o el servicio prestado a la Parte A.", 
tou_h6_p1: "Parte B tiene el derecho de suspender unilateralmente una parte o la totalidad del Servicio si la parte A viola una de las condiciones que se especifican en la sección obligaciones de la Parte A del presente Reglamento o de la Parte B se encontró que tenían anomalías en proceso de colaboración con la Parte A pero los resultados pueden generar los daños para la Parte B o afectar adversamente a los clientes (Parte B no tiene la obligación de presentar pruebas para demostrar). En este caso, la Parte B puede proceder a suspender la prestación de servicios a la Parte A o de otras obligaciones relacionadas con la Parte B bajo este Reglamento.", 
tou_h7_p1: "La parte A puede terminar el uso de los Servicios como no entrar y no cargar dinero al sistema de servicio de la parte B.", 
tou_h7_p2: "Parte B tiene el derecho de terminar unilateralmente el uso de los Servicios por la Parte A en el caso a pedido de los organismos estatales competentes o de otro reglamento de la ley.", 
tou_h7_p3: "Parte B no es responsable de pagar cualquier cantidad de dinero que la Parte A se ha cargado en el Sistema de servicio de la Parte B.", 
tou_h8_p1: "Cualquier controversia que surja entre las dos partes se resolverá en la base de la negociación. Cuando no se alcance un acuerdo como se esperaba, una de las dos partes tiene el derecho de llevar el caso a un tribunal competente en España para buscar su solucion.", 
tou_h8_p2: "Estas disposiciones se hacen en el espíritu voluntario. Parte B tiene el derecho de modificar y sustituir el presente Reglamento mediante un aviso en el sitio web: dmsplus.net conocido por los miembros.", 
tou_h8_p3: "Reglamento modificado tiene virgencia a partir de la fecha de la Decisión de la modificacion entra virgencia. Si la Parte A no está de acuerdo con una modificación de los términos, pueden dejar de utilizar los Servicios. La Parte A usa de los Servicios continuamente después de un reglamento modificado publicado y aplicado, eso llevará significacion que la parte A acepta esta modificación de Reglamento."
 };

var en = {
    
    m_home: "Home",
    m_about: "About",
    m_features:"Features",
    m_price:"Pricing",
    m_manual: "User Manual",
    m_support:"Support",

    btn_signin: "SIGN IN",

    title_statement: "A comprehensive solution to manage the distribution system online by VIETTEL.",

    getting_started: "Getting started",
    getting_started_intro: "DMS PLUS, supported by the latest technology from Viettel, provide you with outstanding features which include online sales, monitoring and positioning support, most advanced sales model through distributors and many more...",
    btn_signup: "SIGN UP",

    about_us: "About Us",
    about_us_intro: "VIT2 - Viettel Information Techology Center is a subsidiary of Viettel Group. Our mission is “never stop making effort to create high quality products and services not only easy to use but fulfill clients’ requirements with desire to bring IT to every corner of life",

    valued_customer: "Valued Customer",

    watch_video: "Watch our video",

    features: "Features",
    features_intro: "Is an overall solution in managing the sale system from the company’s headquarters to the salesman and sales supervisor. It provides online data on sales results, KPI, location and route of salesman, which helps the manager to handle and make decisions...",
    features1: "Improve working quality",
    features1_intro: "Closely supervise the distribution system, effectively manage, control sales activity and inventory at distributors. ",
    features2: "Reduce cost",
    features2_intro1: "Reduce report activities.",
    features2_intro2: "Replace all manual documents by software platform.",
    features3: "Increase business efficiency",
    features3_intro: "Continuously and instantaneously update market information. Provide effective assistance tools accessing sales routes, salesperson’s capacity. ",
    features4: "Securities",
    features4_intro: "System is designed at a level of security that is consistent with the potential harm that could result from the loss, inaccuracy, alteration, unavailability of the data, resources.",

    pricing: "Pricing",
    pricing_basic: "Basic",
    pricing_business: "Business",
    pricing_professional: "Professional",
    pricing_month: "month",
    pricing_unit:"$",
    btn_select: "SELECT",
    pricing_module0: "Module Order",
    pricing_module1: "Module Routing",
    pricing_module2: "Module Visit",
    pricing_module3: "Module Supervise",
    pricing_module4: "Module Report",
    pricing_module5: "Module Promotion",
    pricing_module6: "Module Survey",
    pricing_module7: "Module Inventory",
    pricing_module8: "Module Exchange & Return",
    pricing_module9: "Module Check In",

    screenshot: "Screenshot",
    image1_title: "Login",
    image2_title: "Dashboard",
    image3_title: "Customer's general information",
    image4_title: "Customer's statistic information",
    image5_title: "Choose products",
    image6_title: "Visit customer",
    image7_title: "Visiting customer",
    image8_title: "Visit schedule map",
    image9_title: "Sales detail",
    image10_title: "Sales order detail",
    image11_title: "Register new customer",

    manual: "User Manual",
    manual_website: "Website",
    manual_website_admin: "Admin User Manual",
    manual_website_supervisor: "Supervisor User Manual",
    manual_website_distributor: "Distributor User Manual",
    manual_faq: 'FAQ',
    manual_mobile: "Mobile",
    manual_mobile_supervisor: "Supervisor User Manual",
    manual_mobile_salesman: "Salesman User Manual",

    support: "Support",
    support_intro: "Software Support protects your software investment and empowers your business with world class technical support expertise and comprehensive proactive support.",
    support_phone: "Telephone Support",
    support_phone_intro: "Instruct clients how to process simple incidents and how to use the software.",
    support_tech: "Technical Support",
    support_tech_intro: "Instruct clients to process software incidents remotely via teamviewer and phone with technical team.",
    support_onsite: "On-site Support",
    support_onsite_intro: "Providing directly assist at the place of incidents.",

    contact_us: "Contact us",
    contact_us_intro: "Need help with our solution or looking for more information? We're ready and waiting for your questions.",
    contact_phone: "Phone",
    contact_phone_content: "(+84) 462 881 188",
    contact_address: "Address",
    contact_address_content: "Floor 44, Keangnam Building, Pham Hung Street, Nam Tu Liem District, Hanoi, Vietnam.",
    contact_email: "Email",
    contact_email_content: "vit2_support@viettel.com.vn",

    copyright: "Copyright © 2016 VIETTEL GROUP. All rights reserved.",

    terms_of_use: "Terms of use",

    tou_h1: "1. General Terms", 
tou_h2: "2. Registration Procedure", 
tou_h3: "3. Rights and Responsibilities of Party A", 
tou_h3_1: "Rights of Party A", 
tou_h3_2: "Responsibilities of Party A", 
tou_h4: "4. Rights and Responsibilities of Party B", 
tou_h4_1: "Rights of Party B", 
tou_h4_2: "Responsibilities of Party B", 
tou_h5: "5. About the software provided in service", 
tou_h6: "6. Cease to provide service", 
tou_h7: "7. Cease to use service", 
tou_h8: "8. Applied conditions", 
tou_h1_p1: "By understanding and using our service on website: dmsplus.net you have confirmed and agreed with all terms of use.", 
tou_h1_p2: "Services DMS.Plus, images and website: dmsplus.net are products of intellectual property of Viettel Group. All trademarks, logos, product names contained herein are registered and licensed.", 
tou_h1_p3: "This terms of use apply to DMS.Plus Service Management (hereinafter referred as Service) and all the registered users, on website: dmsone.info).", 
tou_h1_p4: "In this terms and conditions, the party use DMS.Plus service is referred as Party A. The party provide DMS.Plus service is referred as Party B.", 
tou_h2_p1: "When Party A wants to use the service from Party B, Party A register all information required in the website DMSplus.net", 
tou_h2_p2: "A registration code and password of admin account will be sent to Party B", 
tou_h2_p3: "Party B access to the system and create other accounts (supervisor, salesman, etc), select package and activate accounts", 
tou_h3_p1: "Right to use the service.", 
tou_h3_p2: "Request regarding any error of service of Party B according to governing law.", 
tou_h3_p3: "Information of Party A is maintained confidential by Party B.", 
tou_h3_p4: "Manage, utilize service by guidance of Party B and governing law. Responsibilities regarding Interlectual Property Law.", 
tou_h3_p5: "Resposibilities to resolve any dispute related to the use of trademark and information registed in Party'B system. Do not use the service in order to fulfill any illegal activities.", 
tou_h3_p6: "Perform necessary security measure to the service, prevent unauthorized access into Party B system.", 
tou_h3_p7: "Responsibilities regarding all activities within the account of Party A and the risk of loosing access authority.", 
tou_h3_p8: "Cooperate with Party B to fix any error happen in the utilization of service.", 
tou_h4_p1: "Control the utilization of service and DMS.Plus account of Party A according to governing law.", 
tou_h4_p2: "Cease or terminate the service according to this terms of use.", 
tou_h4_p3: "All documents in all mean of form belong to Viettel Group. The right to use service Part B provide Party A does not mean/imply ant transfer of Intelectual Property from Party B to Party A", 
tou_h4_p4: "Upgrade of software: Party B may add, delete, fix, cease the service to upgrade the service.", 
tou_h4_p5: "Give Party A all information in need to use the service.", 
tou_h4_p6: "Provide service, maintenance of service to fulfill client’s need.", 
tou_h4_p7: "Maintain the confidential information of Party A, unless there is a legal request from governing law.", 
tou_h4_p8: "Store the data in the website : dmsplus.net of Party A.", 
tou_h4_p9: "Support Party A in utilization of service (not apply to trial service).", 
tou_h4_p10: "Fulfill request to governing law from party A.", 
tou_h5_p1: "Service includes software for download, this software is able to be updated in device of Party A once available.", 
tou_h5_p2: "Party A proceed the payment by selected package, Part B activate the registered account by Party A", 
tou_h5_p3: "Party A is not allowed to copy, modify, distribute or lease whole, or any part, any softwate in the service provided by Party B.", 
tou_h5_p4: "Party A is fully responsible for lost of account information/ data due to error from Pary A.", 
tou_h5_p5: "Party B do not responsible for the loss of revenue, data, or financial damages, or other damages due to the utilization of service in devices of Party A. In a certain jurisdiction, all responsibilities of party B is limited within the payment proceeded by Party A to use the service provided by Party B.", 
tou_h6_p1: "Party B may cease to provide the whole or any part of service to Party A in case Pary A breach any of Rights and Responsibilities in this terms and conditions, or Party B suspend any activities may cause damage to Party B and other clients from Party A. Party B also has the right to cease to provide other responsibilities in this terms and condition.", 
tou_h7_p1: "Party A may cease to use service by no longer log in the system or proceed payment to Party B.", 
tou_h7_p2: "Party B may terminate the use of service of Party A in case of request from legal enforcement agency.", 
tou_h7_p3: "Party B do not hold any responsibilities to redeem any proceeded payment from Party A.", 
tou_h8_p1: "Any dispute, claim arising out of two parties shall be resolved by negotiation. In case of failure of negotiation, either Party A or Party B may submit to the Court in Vietnam.", 
tou_h8_p2: "Party B own the right to adjust these terms and conditions.", 
tou_h8_p3: "Terms and condition is announced in the website: dmsplus.net . Any adjustment becomes effective from the date of announcement. In case Party A does not agree with the terms and condition, Party A may cease to use the service. By continue to use the service, Party A agree with the terms and condition."
}
